version: 2

config:
  docker: &docker
    - image: circleci/node

  saveCache: &saveCache
    key: v2-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

  restoreCache: &restoreCache
    keys:
      - v2-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  test:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *restoreCache
      - run: npm install
      - save_cache: *saveCache
      - run: npm test

  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *restoreCache
      - run: npm install
      - save_cache: *saveCache
      - run: npm run now-build

workflows:
  version: 2
  test:
    jobs:
      - test
      - build:
          requires:
            - test
